"""create addresses table

Revision ID: 0834398c8f79
Revises: fbbb3ec65969
Create Date: 2021-05-26 15:34:08.924579

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '0834398c8f79'
down_revision = 'fbbb3ec65969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('address_id', postgresql.UUID(as_uuid=True),
                              server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('zip_code', sa.String(), nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
                    sa.Column('street', sa.String(), nullable=True),
                    sa.Column('house_num', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('address_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
