"""init

Revision ID: fbbb3ec65969
Revises:
Create Date: 2021-05-26 15:29:36.050253

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fbbb3ec65969'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('users',
                    sa.Column('user_id', postgresql.UUID(as_uuid=True),
                              server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('date_of_birth', sa.Date(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('height', sa.Float(), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('favourite_color', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('name', 'email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    op.drop_table('users')
    # ### end Alembic commands ###
